version: '3.8'

services:
  # Traefik Reverse Proxy with Let's Encrypt
  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"  # Enable dashboard (optional, for debugging)
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=your-email@example.com"  # Replace with your email
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard (optional)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - web

  # PostgreSQL
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      TZ: America/Los_Angeles
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postgresql.rule=Host(`pg.example.com`)"  # Replace with your subdomain
      - "traefik.http.routers.postgresql.entrypoints=websecure"
      - "traefik.http.routers.postgresql.tls.certresolver=letsencrypt"
      - "traefik.http.services.postgresql.loadbalancer.server.port=5432"
    networks:
      - web

  # MongoDB
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo_data:/data/db
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mongodb.rule=HostSNI(`mongo.example.com`)"  # Replace with your subdomain
      - "traefik.tcp.routers.mongodb.entrypoints=websecure"
      - "traefik.tcp.routers.mongodb.tls.certresolver=letsencrypt"
      - "traefik.tcp.services.mongodb.loadbalancer.server.port=27017"
    networks:
      - web

  # LanceDB
  lancedb:
    image: lancedb/lancedb
    volumes:
      - ./lancedb_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lancedb.rule=Host(`lance.example.com`)"  # Replace with your subdomain
      - "traefik.http.routers.lancedb.entrypoints=websecure"
      - "traefik.http.routers.lancedb.tls.certresolver=letsencrypt"
      - "traefik.http.services.lancedb.loadbalancer.server.port=8080"
    networks:
      - web

  # Qdrant
  qdrant:
    image: qdrant/qdrant
    volumes:
      - ./qdrant_data:/var/lib/qdrant
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qdrant.rule=Host(`qdrant.example.com`)"  # Replace with your subdomain
      - "traefik.http.routers.qdrant.entrypoints=websecure"
      - "traefik.http.routers.qdrant.tls.certresolver=letsencrypt"
      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"
    networks:
      - web

  # NebulaGraph Meta Service
  meta:
    image: vesoft/nebula-metad:v3.6.0
    volumes:
      - ./nebula_data/meta:/var/nebula/meta
      - ./conf/metad.conf:/etc/nebula/metad.conf:ro
    command: /bin/bash -c "chmod 777 /var/nebula/meta && /usr/local/bin/nebula-metad --flagfile=/etc/nebula/metad.conf"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.meta.rule=HostSNI(`meta.example.com`)"  # Replace with your subdomain
      - "traefik.tcp.routers.meta.entrypoints=websecure"
      - "traefik.tcp.routers.meta.tls.certresolver=letsencrypt"
      - "traefik.tcp.services.meta.loadbalancer.server.port=9559"
    networks:
      - web

  # NebulaGraph Graph Service
  graphd:
    image: vesoft/nebula-graphd:v3.6.0
    volumes:
      - ./nebula_data/graphd:/var/nebula/graphd
      - ./conf/graphd.conf:/etc/nebula/graphd.conf:ro
    command: /bin/bash -c "chmod 777 /var/nebula/graphd && /usr/local/bin/nebula-graphd --flagfile=/etc/nebula/graphd.conf"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.graphd.rule=HostSNI(`graph.example.com`)"  # Replace with your subdomain
      - "traefik.tcp.routers.graphd.entrypoints=websecure"
      - "traefik.tcp.routers.graphd.tls.certresolver=letsencrypt"
      - "traefik.tcp.services.graphd.loadbalancer.server.port=9669"
    depends_on:
      - meta
    networks:
      - web

  # NebulaGraph Storage Service
  storaged:
    image: vesoft/nebula-storaged:v3.6.0
    volumes:
      - ./nebula_data/storaged:/var/nebula/storaged
      - ./conf/storaged.conf:/etc/nebula/storaged.conf:ro
    command: /bin/bash -c "chmod 777 /var/nebula/storaged && /usr/local/bin/nebula-storaged --flagfile=/etc/nebula/storaged.conf"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.storaged.rule=HostSNI(`storage.example.com`)"  # Replace with your subdomain
      - "traefik.tcp.routers.storaged.entrypoints=websecure"
      - "traefik.tcp.routers.storaged.tls.certresolver=letsencrypt"
      - "traefik.tcp.services.storaged.loadbalancer.server.port=9779"
    depends_on:
      - meta
    networks:
      - web

networks:
  web:
    driver: bridge